blog/urls.py
from django.urls import path
from blog.views import PostTemplateView, PostListView, PostDetailView, PolicyView


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name= 'home'),
    path('about/', PostTemplateView.as_view(), name= 'about'),
    path('policy/', PolicyView.as_view(), name= 'policy'),
    path('post_detail/<int:pk>', PostDetailView.as_view(), name = 'post_detail')
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

STATUS = (
    (0,'Draft'),
    (1, 'Publish')
)

class Post(models.Model):
    title = models.CharField(max_length=200)
    authur = models.CharField(max_length=100)
    date_updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    status = models.IntegerField(choices= STATUS, default=0)


    class Meta():
        ordering =['-date_created']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post= models.ForeignKey('blog.post',on_delete=models.CASCADE,related_name='comment')
    authur = models.CharField(max_length=100)
    date_updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField() 

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from blog.models import Post

# Create your views here.

class PostTemplateView(TemplateView):
    template_name = 'blog/about.html'

class PolicyView(TemplateView):
    template_name = 'blog/policy.html'

class PostListView(ListView):
    queryset = Post.objects.filter(status=1).order_by('-date_created')
    model = Post
    template_name = 'blog/home.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

blog/templates/blog/about.html
{% extends 'blog/base.html' %}


{% block content %}
<header class="masthead">
    <div class="container-fluid">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-2 mt-2 text-white"> About Us </h3>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
        <div class="card-body">
          <h3 class="text-mute">Who We Are </h3>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate necessitatibus nesciunt fugit? Obcaecati animi, incidunt similique ut exercitationem optio inventore veritatis dolorum tenetur minus nulla consequuntur eos perferendis iusto. Iure!</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi proin sed libero. Eros in cursus turpis massa tincidunt dui ut. Mauris vitae ultricies leo integer malesuada nunc vel risus. Metus aliquam eleifend mi in nulla posuere. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Parturient montes nascetur ridiculus mus mauris vitae. Ornare arcu dui vivamus arcu. Gravida neque convallis a cras semper auctor neque. Vel orci porta non pulvinar neque laoreet suspendisse. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.
            <br>
            Risus in hendrerit gravida rutrum quisque non tellus orci ac. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Volutpat est velit egestas dui id ornare arcu. Facilisis magna etiam tempor orci. Dui accumsan sit amet nulla facilisi morbi. Gravida arcu ac tortor dignissim convallis aenean et tortor. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Commodo viverra maecenas accumsan lacus vel. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mattis enim ut tellus elementum sagittis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Faucibus scelerisque eleifend donec pretium. Magna sit amet purus gravida quis blandit turpis cursus in. Massa sed elementum tempus egestas sed sed risus. Pulvinar elementum integer enim neque. Elementum nisi quis eleifend quam adipiscing vitae proin. Pharetra massa massa ultricies mi. Nibh cras pulvinar mattis nunc.
            <br>
            Tristique nulla aliquet enim tortor. Porta lorem mollis aliquam ut porttitor. Blandit turpis cursus in hac habitasse platea. Arcu ac tortor dignissim convallis aenean et tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. In hac habitasse platea dictumst vestibulum rhoncus est. In vitae turpis massa sed elementum tempus egestas sed sed. Quam quisque id diam vel quam elementum pulvinar etiam. Auctor augue mauris augue neque. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vivamus arcu felis bibendum ut tristique. Quam lacus suspendisse faucibus interdum posuere lorem. Non pulvinar neque laoreet suspendisse interdum. Enim nulla aliquet porttitor lacus luctus. Ut sem viverra aliquet eget sit amet. Id diam vel quam elementum pulvinar. Ipsum faucibus vitae aliquet nec ullamcorper sit.
            <br>
            Vulputate mi sit amet mauris commodo quis imperdiet massa. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Urna et pharetra pharetra massa massa ultricies mi. Venenatis cras sed felis eget velit aliquet sagittis. Quis enim lobortis scelerisque fermentum dui faucibus in. Urna molestie at elementum eu facilisis. Ipsum nunc aliquet bibendum enim facilisis. Nec ullamcorper sit amet risus nullam eget felis eget. Sem et tortor consequat id porta nibh venenatis. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Leo duis ut diam quam. Nulla facilisi etiam dignissim diam. Mauris cursus mattis molestie a iaculis. Id porta nibh venenatis cras sed felis eget velit. Egestas purus viverra accumsan in nisl nisi. Quis auctor elit sed vulputate mi sit. Mauris in aliquam sem fringilla ut. Lobortis feugiat vivamus at augue eget.
            <br>
            Amet nulla facilisi morbi tempus iaculis urna id volutpat. Orci nulla pellentesque dignissim enim. Eu nisl nunc mi ipsum faucibus vitae. Leo a diam sollicitudin tempor. Dui nunc mattis enim ut tellus. Duis convallis convallis tellus id. In fermentum posuere urna nec tincidunt praesent semper feugiat. In tellus integer feugiat scelerisque varius morbi enim. Libero nunc consequat interdum varius sit amet mattis vulputate. Laoreet id donec ultrices tincidunt. Nam aliquam sem et tortor consequat id porta.ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
        </div>
      
     
    
</div>
  
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Code Villa</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
            
    </head>
    

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #75334d;
            border-color: #dc281e;
        }
        .masthead {
            background: #100645;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #122e49;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation bar here -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand text-muted "  href="{% url 'blog:home' %}">Code Villa</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto ">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:about' %}">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:policy' %}">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->

        <div class="container">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Code Villa, Inc</span>
            </div>
          </footer>
        </div>
       
    </body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-2 mt-2 text-white"> Welcome to My Blog </h3>
                    <p class="text-white ">Plenty of article to read </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">Written By {{ post.authur }} On {{ post.date_created}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href=/post_detail/{{post.id}} class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>



{% endblock content %}

blog/templates/blog/policy.html
{% extends 'blog/base.html' %}


{% block content %}
<header class="masthead">
    <div class="container-fluid">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-2 mt-2 text-white"> Policy </h3>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
        <div class="card-body">
          <h3 class="text-mute">Our Policy </h3>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate necessitatibus nesciunt fugit? Obcaecati animi, incidunt similique ut exercitationem optio inventore veritatis dolorum tenetur minus nulla consequuntur eos perferendis iusto. Iure!</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
          <p class="card-text ">Lorem Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi proin sed libero. Eros in cursus turpis massa tincidunt dui ut. Mauris vitae ultricies leo integer malesuada nunc vel risus. Metus aliquam eleifend mi in nulla posuere. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Parturient montes nascetur ridiculus mus mauris vitae. Ornare arcu dui vivamus arcu. Gravida neque convallis a cras semper auctor neque. Vel orci porta non pulvinar neque laoreet suspendisse. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.
            <p>
            Risus in hendrerit gravida rutrum quisque non tellus orci ac. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Volutpat est velit egestas dui id ornare arcu. Facilisis magna etiam tempor orci. Dui accumsan sit amet nulla facilisi morbi. Gravida arcu ac tortor dignissim convallis aenean et tortor. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Commodo viverra maecenas accumsan lacus vel. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mattis enim ut tellus elementum sagittis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Faucibus scelerisque eleifend donec pretium. Magna sit amet purus gravida quis blandit turpis cursus in. Massa sed elementum tempus egestas sed sed risus. Pulvinar elementum integer enim neque. Elementum nisi quis eleifend quam adipiscing vitae proin. Pharetra massa massa ultricies mi. Nibh cras pulvinar mattis nunc.
            </p>
            Tristique nulla aliquet enim tortor. Porta lorem mollis aliquam ut porttitor. Blandit turpis cursus in hac habitasse platea. Arcu ac tortor dignissim convallis aenean et tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. In hac habitasse platea dictumst vestibulum rhoncus est. In vitae turpis massa sed elementum tempus egestas sed sed. Quam quisque id diam vel quam elementum pulvinar etiam. Auctor augue mauris augue neque. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vivamus arcu felis bibendum ut tristique. Quam lacus suspendisse faucibus interdum posuere lorem. Non pulvinar neque laoreet suspendisse interdum. Enim nulla aliquet porttitor lacus luctus. Ut sem viverra aliquet eget sit amet. Id diam vel quam elementum pulvinar. Ipsum faucibus vitae aliquet nec ullamcorper sit.
            <br>
            Vulputate mi sit amet mauris commodo quis imperdiet massa. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Urna et pharetra pharetra massa massa ultricies mi. Venenatis cras sed felis eget velit aliquet sagittis. Quis enim lobortis scelerisque fermentum dui faucibus in. Urna molestie at elementum eu facilisis. Ipsum nunc aliquet bibendum enim facilisis. Nec ullamcorper sit amet risus nullam eget felis eget. Sem et tortor consequat id porta nibh venenatis. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Leo duis ut diam quam. Nulla facilisi etiam dignissim diam. Mauris cursus mattis molestie a iaculis. Id porta nibh venenatis cras sed felis eget velit. Egestas purus viverra accumsan in nisl nisi. Quis auctor elit sed vulputate mi sit. Mauris in aliquam sem fringilla ut. Lobortis feugiat vivamus at augue eget.
            <br>
            Amet nulla facilisi morbi tempus iaculis urna id volutpat. Orci nulla pellentesque dignissim enim. Eu nisl nunc mi ipsum faucibus vitae. Leo a diam sollicitudin tempor. Dui nunc mattis enim ut tellus. Duis convallis convallis tellus id. In fermentum posuere urna nec tincidunt praesent semper feugiat. In tellus integer feugiat scelerisque varius morbi enim. Libero nunc consequat interdum varius sit amet mattis vulputate. Laoreet id donec ultrices tincidunt. Nam aliquam sem et tortor consequat id porta.ipsum dolor sit amet consectetur adipisicing elit. Deserunt provident molestiae, quo ad possimus odit quas quia quasi aut ipsa sint ex quidem officia sed corporis quae minus labore inventore?</p>
        </div>
      
     
    
</div>
  
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} 

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.authur }} | {{ post.date_created }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #46709a;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right  ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body card-end">
        <p class="card-text"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem fugiat dignissimos, similique animi, unde quos tempore deserunt officia delectus ipsa quo dolorem natus ipsum ea harum laborum alias, neque quisquam.</p>
        <a href="{% url 'blog:about' %}"class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>


{% endblock sidebar %}